# Generated by Django 4.1.7 on 2023-03-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='courser',
            new_name='course',
        ),
    ]
